### PR TITLE
Batch Converts all audio to opus.

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://github.com/Iamgoofball/AOV-Update/tree/master/The%20Nightmare%20Update/base/sounds
github broke check audio files here

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this is on hold until someone with client repo access merges the fix over there and compiles the client again

**Comment by oldmud0** [comment]
you don't need to merge before compiling - in fact it is favorable to compile before merging so you can test if your changes actually work.

**Comment by Iamgoofball** [comment]
of course, that'd be great if we had anyone actively able to compile the client right now who has not opted out due to drama or personal reasons.

**Comment by Iamgoofball** [comment]
With https://github.com/AttorneyOnlineVidya/AO2-Client/pull/5 merged we can now proceed with this PR. I've got everything converted locally to remake this when the next folder name is decided on and shit.

**Pull request closed without merging**
